### ISSUE TITLE
Fix WebException in - [Socket Connect(System.Net.EndPoint remoteEP)]

### ISSUE THREAD

**Issue by aditmer** [aditmer/NightscoutHybridMobile#10]
### Stacktrace ###

<pre>0 System.Net.Sockets Socket Connect 1 System.Net WebConnection Connect 2 System.Net HttpWebRequest EndGetResponse 3 System.Threading.Tasks TaskFactory`1[TResult] FromAsyncCoreLogic null 0 </pre>

### Reason ###

System.Net.WebException: Error: ConnectFailure (Connection refused) ---> System.Net.Sockets.SocketException: Connection refused

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/420647/crash_reasons/149799992](https://rink.hockeyapp.net/manage/apps/420647/crash_reasons/149799992)

**Comment by srmoss** [comment]
Hmmm... this failed on the status.json.  I wonder if this was a typo, or if someone's site isn't responding to the status API?

I can't tell who the user is... Is that not possible with these in HockeyApp?

**Comment by aditmer** [comment]
This was the typo crash we saw earlier.  It should be fixed now w/ my try/catch block.  I'm closing this.
