### ISSUE TITLE
Button Styles

### ISSUE THREAD

**Issue by hackingtype1** [aditmer/NightscoutHybridMobile#16]
UI suggestion: enlarge font size on main screen buttons and/or match button styles between main view & settings view.  Maybe center the buttons on settings page?

**Comment by aditmer** [comment]
1. I enlarged the font on iOS.  On Android it causes the words to wrap in the button so I didn't change it there.
2. I changed the style to have the gray background like the settings page.  Thoughts?
3. I chose not to center the buttons on the settings page.
