### ISSUE TITLE
Re-register with iOS APNs during launch

### ISSUE THREAD

**Issue by srmoss** [aditmer/NightscoutHybridMobile#38]
@sobrecht found that during app upgrade, APNs disposes of her device token and therefore notifications are no longer delivered.

According to [this stackoverflow](http://stackoverflow.com/questions/6652242/does-the-apns-device-token-ever-change-once-created/34007364#34007364), and [this Apple doc](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/APNSOverview.html#//apple_ref/doc/uid/TP40008194-CH8-SW1), we should probably be re-registering every time the app launches.

To accommodate this, we should:
1. Register with APNs during app launch
2. Compare the device token with the InstallationID
3. If different, un-register with the old InstallationID (if not null)
4. And re-register with the new InstallationID

This will ensure the disposed device token is also no longer in ANH/NS.

**Comment by aditmer** [comment]
I think I have this resolved.  We should test with server logging before I push a new build.
