### ISSUE TITLE
Fix WebException in - [HttpWebRequest EndGetResponse(System.IAsyncResult asyncResult)]

### ISSUE THREAD

**Issue by aditmer** [aditmer/NightscoutHybridMobile#7]
### Stacktrace ###

<pre>0 System.Net HttpWebRequest EndGetResponse 1 System.Threading.Tasks TaskFactory`1[TResult] FromAsyncCoreLogic null 0 </pre>

### Reason ###

System.Net.WebException: Error: NameResolutionFailure

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/420647/crash_reasons/149750654](https://rink.hockeyapp.net/manage/apps/420647/crash_reasons/149750654)

**Comment by srmoss** [comment]
Duplicate of #8
