### ISSUE TITLE
Fix WebException in HttpWebRequest.EndGetResponse

### ISSUE THREAD

**Issue by aditmer** [aditmer/NightscoutHybridMobile#8]
### Stacktrace ###

<pre>0 System.Net HttpWebRequest EndGetResponse 1 System.Threading.Tasks TaskFactory`1[TResult] FromAsyncCoreLogic 2 System.Runtime.ExceptionServices ExceptionDispatchInfo Throw 3 System.Runtime.CompilerServices TaskAwaiter ThrowForNonSuccess 4 System.Runtime.CompilerServices TaskAwaiter HandleNonSuccessAndDebuggerNotification 5 System.Runtime.CompilerServices TaskAwaiter ValidateEnd 6 System.Runtime.CompilerServices ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult] GetResult 7 System.Net.Http HttpClientHandler+<SendAsync>c__async0 MoveNext 8 System.Runtime.ExceptionServices ExceptionDispatchInfo Throw 9 System.Runtime.CompilerServices TaskAwaiter ThrowForNonSuccess 10 System.Runtime.CompilerServices TaskAwaiter HandleNonSuccessAndDebuggerNotification 11 System.Runtime.CompilerServices TaskAwaiter ValidateEnd 12 System.Runtime.CompilerServices ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult] GetResult 13 System.Net.Http HttpClient+<SendAsyncWorker>c__async0 MoveNext 14 System.Runtime.ExceptionServices ExceptionDispatchInfo Throw 15 System.Runtime.CompilerServices TaskAwaiter ThrowForNonSuccess 16 System.Runtime.CompilerServices TaskAwaiter HandleNonSuccessAndDebuggerNotification 17 System.Runtime.CompilerServices TaskAwaiter ValidateEnd 18 System.Runtime.CompilerServices TaskAwaiter`1[TResult] GetResult 19 NightscoutMobileHybrid Webservices+<GetStatusJson>c__async1 MoveNext 20 System.Runtime.ExceptionServices ExceptionDispatchInfo Throw 21 System.Runtime.CompilerServices TaskAwaiter ThrowForNonSuccess 22 System.Runtime.CompilerServices TaskAwaiter HandleNonSuccessAndDebuggerNotification 23 System.Runtime.CompilerServices TaskAwaiter ValidateEnd 24 System.Runtime.CompilerServices TaskAwaiter GetResult 25 NightscoutMobileHybrid SettingsPage+<btnSave_Clicked>c__async0 MoveNext 26 System.Runtime.ExceptionServices ExceptionDispatchInfo Throw 27 System.Runtime.CompilerServices AsyncMethodBuilderCore <ThrowAsync>m__0 28 Android.App SyncContext+<Post>c__AnonStorey0 <>m__0 29 Java.Lang Thread+RunnableImplementor Run 30 Java.Lang IRunnableInvoker n_Run 31 mono.java.lang RunnableImplementor n_run 32 mono.java.lang RunnableImplementor run 33 android.os Handler handleCallback 34 android.os Handler dispatchMessage 35 android.os Looper loop 36 android.app ActivityThread main 37 java.lang.reflect Method invoke 38 com.android.internal.os ZygoteInit$MethodAndArgsCaller run 39 com.android.internal.os ZygoteInit main Java.Lang.Thread 2 </pre>

### Reason ###

android.runtime.JavaProxyThrowable: System.Net.WebException: Error: NameResolutionFailure

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/420648/crash_reasons/149754900](https://rink.hockeyapp.net/manage/apps/420648/crash_reasons/149754900)

**Comment by srmoss** [comment]
This is caused by a typo in the URL.  Need to add try/catch at the service call level in WebService.GetStatusJson.

**Comment by aditmer** [comment]
Fixed in next release.
