### ISSUE TITLE
Fix RuntimeException in Camera.native_getParameters

### ISSUE THREAD

**Issue by aditmer** [aditmer/NightscoutHybridMobile#9]
### Stacktrace ###

<pre>0 android.hardware Camera native_getParameters 1 android.hardware Camera getParameters 2 md5270abb39e60627f0f200893b490a1ade SwitchRenderer n_onCheckedChanged 3 md5270abb39e60627f0f200893b490a1ade SwitchRenderer onCheckedChanged 4 android.widget CompoundButton setChecked 5 android.support.v7.widget SwitchCompat setChecked 6 android.support.v7.widget SwitchCompat toggle 7 android.widget CompoundButton performClick 8 android.view View$PerformClick run 9 android.os Handler handleCallback 10 android.os Handler dispatchMessage 11 android.os Looper loop 12 android.app ActivityThread main 13 java.lang.reflect Method invoke 14 com.android.internal.os ZygoteInit$MethodAndArgsCaller run 15 com.android.internal.os ZygoteInit main 16 System.Runtime.ExceptionServices ExceptionDispatchInfo Throw 17 Java.Interop JniEnvironment+InstanceMethods CallObjectMethod 18 Java.Interop JniPeerMembers+JniInstanceMethods InvokeVirtualObjectMethod 19 Android.Hardware Camera GetParameters 20 Lamp.Plugin LampImplementation TurnOff 21 NightscoutMobileHybrid NightscoutMobileHybridPage SwLight_Toggled 22 Xamarin.Forms Switch+<>c <.cctor>b__8_0 23 Xamarin.Forms BindableObject SetValueActual 24 Xamarin.Forms BindableObject SetValueCore 25 Xamarin.Forms BindableObject SetValueCore 26 Xamarin.Forms.Element.Xamarin.Forms IElementController SetValueFromRenderer 27 Xamarin.Forms.Platform.Android.AppCompat.SwitchRenderer.Android.Widget.CompoundButton IOnCheckedChangeListener OnCheckedChanged 28 Android.Widget CompoundButton+IOnCheckedChangeListenerInvoker n_OnCheckedChanged_Landroid_widget_CompoundButton_Z 29 android.hardware Camera native_getParameters 30 android.hardware Camera getParameters 31 md5270abb39e60627f0f200893b490a1ade SwitchRenderer n_onCheckedChanged 32 md5270abb39e60627f0f200893b490a1ade SwitchRenderer onCheckedChanged 33 android.widget CompoundButton setChecked 34 android.support.v7.widget SwitchCompat setChecked 35 android.support.v7.widget SwitchCompat toggle 36 android.widget CompoundButton performClick 37 android.view View$PerformClick run 38 android.os Handler handleCallback 39 android.os Handler dispatchMessage 40 android.os Looper loop 41 android.app ActivityThread main 42 java.lang.reflect Method invoke 43 com.android.internal.os ZygoteInit$MethodAndArgsCaller run 44 com.android.internal.os ZygoteInit main java.lang.reflect 2 </pre>

### Reason ###

Java.Lang.RuntimeException: getParameters failed (empty parameters)

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/420648/crash_reasons/149755449](https://rink.hockeyapp.net/manage/apps/420648/crash_reasons/149755449)

**Comment by srmoss** [comment]
Caused by two toggles of the light switch on Android.

**Comment by srmoss** [comment]
Seems to be device specific.

**Comment by aditmer** [comment]
I'll have to dig into the Android implementation of this plugin:  https://github.com/kphillpotts/Xamarin.Plugins/tree/master/Lamp

**Comment by srmoss** [comment]
[This](http://stackoverflow.com/questions/14941625/correct-handling-of-exception-getparameters-failed-empty-parameters) might help

**Comment by aditmer** [comment]
Fixed in latest beta release.  Had to do a custom implementation of the Lamp plugin on Android.
